### PR TITLE
Gitpod_edits

### PR DESCRIPTION
**Pull request by chriswyatt1**
Gitpod edits to that usearch is turned off

### CODE REVIEW

**Review by chriswyatt1 — COMMENTED** [review]
I think it merges ok with main.

**Comment by chriswyatt1** [comment]
runner fails on cutadapt test. So will run the tests again and replace the snapshots

**Comment by chriswyatt1** [comment]
Action runner passes. I check cutadpat output is what I expect, then replaced the snapshot

**Comment by SimonDMurray** [comment]
@chriswyatt1 awsome! everything looks good. feel free to delete your branch :)

**Comment by chriswyatt1** [comment]
Thanks

**Pull request merged**
